# Unordered list style
# https://github.com/DavidAnson/markdownlint/blob/main/doc/md004.md
MD004: false

# Unordered list indentation
# https://github.com/DavidAnson/markdownlint/blob/main/doc/md007.md
MD007: false

# Hard tabs
# https://github.com/DavidAnson/markdownlint/blob/main/doc/md010.md
MD010:
  code_blocks: false

# Multiple consecutive blank lines
# https://github.com/DavidAnson/markdownlint/blob/main/doc/md012.md
MD012:
  maximum: 2

# Line length
# https://github.com/DavidAnson/markdownlint/blob/main/doc/md013.md
MD013: false

# Spaces after list markers
# https://github.com/DavidAnson/markdownlint/blob/main/doc/md030.md
MD030: false

# Inline HTML
# https://github.com/DavidAnson/markdownlint/blob/main/doc/md033.md
MD033: false

# First line heading
# https://github.com/DavidAnson/markdownlint/blob/main/doc/md041.md
MD041: false
